# Generated by Django 6.0 on 2025-12-12 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaParametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='admin_panel.informe')),
                ('parametro_obligatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.parametroobligatorio')),
                ('parametro_opcional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.parametroopcional')),
            ],
        ),
    ]
