# Generated by Django 6.0 on 2025-12-13 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_respuestaparametro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='informe',
            name='autor',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='informes_creados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informe',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informes_inspeccionados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='informe',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.componente'),
        ),
    ]
